# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BlockwiseQuantization(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BlockwiseQuantization()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBlockwiseQuantization(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BlockwiseQuantizationBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # BlockwiseQuantization
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BlockwiseQuantization
    def Scales(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BlockwiseQuantization
    def ZeroPoints(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BlockwiseQuantization
    def BlockSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def BlockwiseQuantizationStart(builder):
    builder.StartObject(3)

def Start(builder):
    BlockwiseQuantizationStart(builder)

def BlockwiseQuantizationAddScales(builder, scales):
    builder.PrependInt32Slot(0, scales, 0)

def AddScales(builder, scales):
    BlockwiseQuantizationAddScales(builder, scales)

def BlockwiseQuantizationAddZeroPoints(builder, zeroPoints):
    builder.PrependInt32Slot(1, zeroPoints, 0)

def AddZeroPoints(builder, zeroPoints):
    BlockwiseQuantizationAddZeroPoints(builder, zeroPoints)

def BlockwiseQuantizationAddBlockSize(builder, blockSize):
    builder.PrependInt32Slot(2, blockSize, 0)

def AddBlockSize(builder, blockSize):
    BlockwiseQuantizationAddBlockSize(builder, blockSize)

def BlockwiseQuantizationEnd(builder):
    return builder.EndObject()

def End(builder):
    return BlockwiseQuantizationEnd(builder)
